### ISSUE TITLE
Error with envd

### ISSUE THREAD

**Issue by vuminhquang** [kemingy/vllm-env#2]
Hello,
I have git installed and could be found in the PATH. However, envd could not see it.
""""""""""""""""""
ERROR [internal] pip install git+https://github.com/vllm-project..
 ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
""""""""""""""""""
Thank you

**Comment by vuminhquang** [comment]
Update: I just try with trying to set PATH directly, but no different
PATH=$PATH:/usr/bin:/opt/conda/envs/envd/bin envd build -f :serving

**Comment by kemingy** [comment]
`git` is installed in the `base(dev=True)`. Will need to add it if you're using `:sering` instead of `build`.

**Comment by kemingy** [comment]
I have updated the envd config file. You can try it again.

**Comment by vuminhquang** [comment]
I found that envd is pretty good to use and plan to use for vllm in production. I have some questions hope you could help too.
1. Do dev=True affect the production?
2. Could I change the PATH directly in build.envd (not for this git case)?
Thank you.

**Comment by kemingy** [comment]
1. Not really. dev=True means that it will install some libraries that are useful for development like git, vim, etc.
2. Yes. `runtime.environ(env={"ENVD_MODE": "DEV"}, extra_path=["/usr/bin/go/bin"])` the extra_path will be added to PATH. ref https://envd.tensorchord.ai/api/starlark/v1/runtime.html#environ

**Comment by vuminhquang** [comment]
> I have updated the envd config file. You can try it again.

Thank you for your blaze support and the questions answered :D, fixed my problem.
